name: PrimumNonNocere
version: '${project.version}'
main: com.jliii.primumnonnocere.PrimumNonNocere
api-version: 1.19
commands:
  softmute:
    description: TheatriaChat command
    usage: /softmute <player>
    aliases: [sm]